// export const sampleLeaderMeetings: LeaderMeetingCardProps[] = [
//   {
//     status: '모집중',
//     deadline: '2025-06-15',
//     title: '느리게 걷기 & 대화',
//     date: '2025-06-20',
//     location: '서울특별시 송파구 석촌동',
//     count: 4,
//     likes: 32,
//     applicants: 6,
//   },
//   {
//     status: '완료',
//     deadline: '2025-05-10',
//     title: '명상과 산책',
//     date: '2025-05-15',
//     location: '서울특별시 마포구 연남동',
//     count: 2,
//     likes: 18,
//     applicants: 10,
//     averageRating: 4.3,
//   },
//   {
//     status: '모집중',
//     deadline: '2025-06-30',
//     title: '디지털 기초교육 A반',
//     date: '2025-07-02',
//     location: '서울특별시 노원구 공릉동',
//     count: 6,
//     likes: 25,
//     applicants: 8,
//   },
//   {
//     status: '완료',
//     deadline: '2025-04-01',
//     title: '사진과 함께 걷는 길',
//     date: '2025-04-05',
//     location: '서울특별시 종로구 인사동',
//     count: 3,
//     likes: 41,
//     applicants: 15,
//     averageRating: 4.7,
//   },
//   {
//     status: '모집중',
//     deadline: '2025-07-05',
//     title: '동네 음악회 기획 워크숍',
//     date: '2025-07-10',
//     location: '서울특별시 강서구 화곡동',
//     count: 5,
//     likes: 12,
//     applicants: 3,
//   },
// ];
